### ISSUE TITLE
FEATURE: support custom backgrounds

### ISSUE THREAD

**Issue by matthew-piziak** [mattearly/dmpower-dungeons-and-dragons-5e#81]
My character has a custom background, but I don't see a way to support this in the character creator.

**Comment by mattearly** [comment]
I would like to add this option in at some point

**Comment by mattearly** [comment]
what would suffice here? I was thinking, most backgrounds offer 4 things between languages, skills, tools.

I could add an option for Custom: type in background name and then it lets you choose a custom pick of langs, skills, and tools that would fit your background

**Comment by mattearly** [comment]
done in build9 using default dmg rules
